server:
  port: 8082

spring:
  application:
    name: venue-service
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_platform
    username: booking
    password: 123123
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: venue_schema
  flyway:
    enabled: true
    schemas: venue_schema
    default-schema: venue_schema
    create-schemas: true
    locations: classpath:db/migration

app:
  jwt:
    secret: ${JWT_SECRET:change-me-to-a-very-long-secret-key-at-least-256-bits-long!!}
  seed:
    enabled: true
