server:
  port: 8085

spring:
  application:
    name: notification-service
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:2525}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  mail:
    from: ${MAIL_FROM:booking-platform@example.com}
    fallback-to: ${MAIL_FALLBACK_TO:notifications@example.com}
  sqs:
    endpoint: ${AWS_ENDPOINT:http://localhost:4566}
    region: ${AWS_REGION:ap-southeast-1}
    access-key: ${AWS_ACCESS_KEY_ID:test}
    secret-key: ${AWS_SECRET_ACCESS_KEY:test}
    booking-events-queue: booking-events
    consumer-enabled: true
    consumer-poll-interval-ms: 2000
    consumer-batch-size: 10
    consumer-wait-time-seconds: 1
